#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

std::int64_t solve(const std::int64_t &a, const int64_t &b, const int64_t &c) {
    // TODO: edit here
    int out;
    if (a==b) out = c;
    else if (b==c) out = a;
    else out = b;

    return out;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    // failed to analyze input format
    // TODO: edit here

    std::vector<int64_t> a(2), b(2), c(2);
    REP (i, 2) { std::cin >> a[i]; }
    REP (i, 2) { std::cin >> b[i]; }
    REP (i, 2) { std::cin >> c[i]; }

    int64_t x = solve(a[0], b[0], c[0]);
    int64_t y = solve(a[1], b[1], c[1]);
    std::cout << x << ' ' << y << '\n';
    return 0;
}
